/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package pichisUI;

import java.awt.CardLayout;
import java.awt.Color;
import java.awt.GraphicsEnvironment;
import java.awt.Rectangle;
import java.util.ArrayList;
import javax.swing.DefaultListModel;
import javax.swing.JFrame;
import javax.swing.JOptionPane;
import pichisBD.*;
import pichisNF.*;

/**
 *
 * @author Johann
 */
public class InterfaceAdministratif extends javax.swing.JFrame {

    private Administratif administratif;
    private DefaultListModel<DPI> modeleListeDPI;
    private DefaultListModel<Sejour> modeleListeSejour;
    private DefaultListModel<Prestations> modeleListePrestation;
    private DefaultListModel<DPI> modeleListeDPIRecherche;
    
    private DAOSejour daoSejour; 
    private DAODPI daoDpi;
    private DAOLocalisation daoLoc;
    private DAOServices daoService;
    private DAOPrestations daoPrestations;
    private Administratif a;
    /**
     * Creates new form InterfaceAdministratif
     */

    GraphicsEnvironment graphicsEnvironment = GraphicsEnvironment.getLocalGraphicsEnvironment();
    Rectangle maximumWindowBounds = graphicsEnvironment.getMaximumWindowBounds();
    int width = (int) (maximumWindowBounds.width - 0.015 * maximumWindowBounds.width);
    int height = (int) (maximumWindowBounds.height - 0.02 * maximumWindowBounds.height);

    public InterfaceAdministratif(Administratif a) {
        this.a = a;
        initComponents();
        
        modeleListeDPI = new DefaultListModel<DPI>();
        modeleListeSejour = new DefaultListModel<Sejour>();
        modeleListePrestation = new DefaultListModel<Prestations>();
        daoDpi = new DAODPI();
        daoSejour = new DAOSejour();
        daoLoc = new DAOLocalisation();
        daoService = new DAOServices();
        daoPrestations = new DAOPrestations();
        //Définit un titre pour notre fenêtre
        setTitle("PICHIS Administratif");

        //this.setResizable(false);
        //Nous demandons maintenant à notre objet de se positionner au centre
        setLocationRelativeTo(null);

        setDefaultCloseOperation(JFrame.EXIT_ON_CLOSE);
        //Termine le processus lorsqu'on clique sur la croix rouge
        
        this.setDefaultLookAndFeelDecorated(true);

        setSize(maximumWindowBounds.width, maximumWindowBounds.height);
        this.pack();

        comboBoxService.setModel(new javax.swing.DefaultComboBoxModel(Specialite.values()));
        comboBoxService.setEnabled(false);
        comboBoxPlacement.setEnabled(false);

        this.affichageListeDePatients();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        InterfaceAdministratif = new javax.swing.JPanel();
        panelTitre = new javax.swing.JPanel();
        PanelBarreTitre = new javax.swing.JPanel();
        image = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel37 = new javax.swing.JLabel();
        jLabel38 = new javax.swing.JLabel();
        panelBarreRecherche = new javax.swing.JPanel();
        labelRecherche = new javax.swing.JLabel();
        jTextFieldRecherche = new javax.swing.JTextField();
        LabelBoutonRecherche = new javax.swing.JLabel();
        panelListe = new javax.swing.JPanel();
        scrollPaneListePatient = new javax.swing.JScrollPane();
        listeDePatients = new javax.swing.JList();
        boutonAjouter = new javax.swing.JButton();
        panelPrincipal = new javax.swing.JPanel();
        DMA = new javax.swing.JPanel();
        panelDouverture = new javax.swing.JPanel();
        jLabel14 = new javax.swing.JLabel();
        panelOnglets = new javax.swing.JTabbedPane();
        ongletFichePatient = new javax.swing.JPanel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        textFieldNom = new javax.swing.JTextField();
        textFieldPrenom = new javax.swing.JTextField();
        textFieldSexe = new javax.swing.JTextField();
        textFieldIPP = new javax.swing.JTextField();
        textFieldDateNaissance = new javax.swing.JTextField();
        textFieldAdresse = new javax.swing.JTextField();
        ongletLocalisation = new javax.swing.JPanel();
        jPanel1 = new javax.swing.JPanel();
        boutonEnregistrer = new javax.swing.JButton();
        boutonModifier = new javax.swing.JButton();
        labelPlacement = new javax.swing.JLabel();
        comboBoxPlacement = new javax.swing.JComboBox();
        champNumeroChambre = new javax.swing.JTextField();
        labelNumeroChambre = new javax.swing.JLabel();
        labelService = new javax.swing.JLabel();
        comboBoxService = new javax.swing.JComboBox();
        ongletSejour = new javax.swing.JPanel();
        jScrollSejours = new javax.swing.JScrollPane();
        listeSejours = new javax.swing.JList();
        panelSejour = new javax.swing.JPanel();
        labelDateEntree = new javax.swing.JLabel();
        champJourEntree = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        champMoisEntree = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        champAnneeEntree = new javax.swing.JTextField();
        labelDateSortie = new javax.swing.JLabel();
        champJourSortie = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        champMoisSortie = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        champAnneeSortie = new javax.swing.JTextField();
        labelNumeroSejour = new javax.swing.JLabel();
        champNumeroSejour = new javax.swing.JTextField();
        labelPhResponsable = new javax.swing.JLabel();
        champPhResponsable = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        listePrestations = new javax.swing.JList();
        boutonAjouterSejour = new javax.swing.JButton();
        ongletLettreSortie = new javax.swing.JPanel();
        jScrollPane2 = new javax.swing.JScrollPane();
        texteLettreSortie = new javax.swing.JTextArea();
        boutonFermerDPI = new javax.swing.JButton();
        panelDPIFerme = new javax.swing.JPanel();
        boutonOuvrirDPI = new javax.swing.JButton();
        labelFerme = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setFocusTraversalPolicyProvider(true);
        getContentPane().setLayout(new javax.swing.BoxLayout(getContentPane(), javax.swing.BoxLayout.LINE_AXIS));

        InterfaceAdministratif.setBackground(new java.awt.Color(229, 229, 229));
        InterfaceAdministratif.setPreferredSize(new java.awt.Dimension(width, height));
        InterfaceAdministratif.setLayout(new java.awt.BorderLayout());

        panelTitre.setLayout(new java.awt.BorderLayout());

        PanelBarreTitre.setBackground(new java.awt.Color(255, 255, 255));
        PanelBarreTitre.setPreferredSize(new java.awt.Dimension(1550, 165));

        image.setIcon(new javax.swing.ImageIcon(getClass().getResource("/data/Images/noun_43356_cc1.png"))); // NOI18N

        jLabel9.setFont(new java.awt.Font("Garamond", 0, 24)); // NOI18N
        jLabel9.setText(a.getPrenom());

        jLabel10.setFont(new java.awt.Font("Garamond", 0, 36)); // NOI18N
        jLabel10.setText(a.getNom());

        jLabel11.setFont(new java.awt.Font("Trajan Pro", 0, 37)); // NOI18N
        jLabel11.setText("Personnel administratif");

        jLabel37.setIcon(new javax.swing.ImageIcon(getClass().getResource("/data/Images/iconmonstr-wrench-20-icon-64.png"))); // NOI18N
        jLabel37.setText("Préférences");
        jLabel37.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jLabel37.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jLabel37.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);

        jLabel38.setIcon(new javax.swing.ImageIcon(getClass().getResource("/data/Images/iconmonstr-logout-3-icon-64.png"))); // NOI18N
        jLabel38.setText("Déconnexion");
        jLabel38.setVerticalAlignment(javax.swing.SwingConstants.TOP);
        jLabel38.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jLabel38.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jLabel38.setIconTextGap(0);
        jLabel38.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        jLabel38.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel38MouseClicked(evt);
            }
        });

        javax.swing.GroupLayout PanelBarreTitreLayout = new javax.swing.GroupLayout(PanelBarreTitre);
        PanelBarreTitre.setLayout(PanelBarreTitreLayout);
        PanelBarreTitreLayout.setHorizontalGroup(
            PanelBarreTitreLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PanelBarreTitreLayout.createSequentialGroup()
                .addComponent(image)
                .addGroup(PanelBarreTitreLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(PanelBarreTitreLayout.createSequentialGroup()
                        .addGap(27, 27, 27)
                        .addGroup(PanelBarreTitreLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel10, javax.swing.GroupLayout.PREFERRED_SIZE, 271, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel9, javax.swing.GroupLayout.PREFERRED_SIZE, 271, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(PanelBarreTitreLayout.createSequentialGroup()
                        .addGap(24, 24, 24)
                        .addComponent(jLabel11, javax.swing.GroupLayout.PREFERRED_SIZE, 569, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 365, Short.MAX_VALUE)
                .addComponent(jLabel37)
                .addGap(86, 86, 86)
                .addComponent(jLabel38)
                .addGap(44, 44, 44))
        );
        PanelBarreTitreLayout.setVerticalGroup(
            PanelBarreTitreLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, PanelBarreTitreLayout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(image, javax.swing.GroupLayout.PREFERRED_SIZE, 163, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, PanelBarreTitreLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel10, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0)
                .addComponent(jLabel9)
                .addGap(0, 0, 0)
                .addComponent(jLabel11)
                .addGap(34, 34, 34))
            .addGroup(PanelBarreTitreLayout.createSequentialGroup()
                .addGap(41, 41, 41)
                .addGroup(PanelBarreTitreLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel37)
                    .addComponent(jLabel38))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        panelTitre.add(PanelBarreTitre, java.awt.BorderLayout.PAGE_START);

        panelBarreRecherche.setBackground(new java.awt.Color(230, 230, 230));
        panelBarreRecherche.setBorder(javax.swing.BorderFactory.createTitledBorder(""));
        panelBarreRecherche.setPreferredSize(new java.awt.Dimension(1550, 60));
        panelBarreRecherche.setLayout(new javax.swing.BoxLayout(panelBarreRecherche, javax.swing.BoxLayout.LINE_AXIS));

        labelRecherche.setFont(new java.awt.Font("Garamond", 1, 14)); // NOI18N
        labelRecherche.setText("Rechercher un patient :");
        panelBarreRecherche.add(labelRecherche);

        jTextFieldRecherche.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createTitledBorder("")));
        jTextFieldRecherche.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextFieldRechercheActionPerformed(evt);
            }
        });
        jTextFieldRecherche.addInputMethodListener(new java.awt.event.InputMethodListener() {
            public void caretPositionChanged(java.awt.event.InputMethodEvent evt) {
            }
            public void inputMethodTextChanged(java.awt.event.InputMethodEvent evt) {
                jTextFieldRechercheInputMethodTextChanged(evt);
            }
        });
        jTextFieldRecherche.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                jTextFieldRechercheKeyReleased(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt) {
                jTextFieldRechercheKeyTyped(evt);
            }
        });
        panelBarreRecherche.add(jTextFieldRecherche);

        LabelBoutonRecherche.setIcon(new javax.swing.ImageIcon(getClass().getResource("/data/Images/iconmonstr-magnifier-5-icon-32.png"))); // NOI18N
        panelBarreRecherche.add(LabelBoutonRecherche);

        panelTitre.add(panelBarreRecherche, java.awt.BorderLayout.PAGE_END);

        InterfaceAdministratif.add(panelTitre, java.awt.BorderLayout.PAGE_START);

        panelListe.setBorder(javax.swing.BorderFactory.createTitledBorder("Patients"));
        panelListe.setMinimumSize(new java.awt.Dimension(270, 69));
        panelListe.setLayout(new java.awt.BorderLayout());

        scrollPaneListePatient.setMinimumSize(new java.awt.Dimension(258, 23));

        listeDePatients.setBackground(new java.awt.Color(204, 204, 204));
        listeDePatients.setBorder(javax.swing.BorderFactory.createTitledBorder(""));
        listeDePatients.setFont(new java.awt.Font("SimHei", 0, 18)); // NOI18N
        listeDePatients.setModel(new javax.swing.AbstractListModel() {
            ArrayList<pichisNF.DPI> listeDpi = new ArrayList<pichisNF.DPI>();
            public int getSize() { return listeDpi.size(); }
            public Object getElementAt(int i) { return listeDpi.get(i); }
        });
        listeDePatients.setMinimumSize(new java.awt.Dimension(2, 0));
        listeDePatients.addListSelectionListener(new javax.swing.event.ListSelectionListener() {
            public void valueChanged(javax.swing.event.ListSelectionEvent evt) {
                listeDePatientsValueChanged(evt);
            }
        });
        scrollPaneListePatient.setViewportView(listeDePatients);

        panelListe.add(scrollPaneListePatient, java.awt.BorderLayout.WEST);

        boutonAjouter.setText("Nouveau patient");
        boutonAjouter.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                boutonAjouterActionPerformed(evt);
            }
        });
        panelListe.add(boutonAjouter, java.awt.BorderLayout.PAGE_END);

        InterfaceAdministratif.add(panelListe, java.awt.BorderLayout.WEST);
        panelListe.getAccessibleContext().setAccessibleName("");

        panelPrincipal.setLayout(new java.awt.BorderLayout());

        DMA.setPreferredSize(new java.awt.Dimension(width, height));
        DMA.setLayout(new java.awt.CardLayout());

        jLabel14.setFont(new java.awt.Font("MingLiU_HKSCS-ExtB", 0, 18)); // NOI18N
        jLabel14.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel14.setText("Sélectionner un patient");

        javax.swing.GroupLayout panelDouvertureLayout = new javax.swing.GroupLayout(panelDouverture);
        panelDouverture.setLayout(panelDouvertureLayout);
        panelDouvertureLayout.setHorizontalGroup(
            panelDouvertureLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelDouvertureLayout.createSequentialGroup()
                .addGap(210, 210, 210)
                .addComponent(jLabel14, javax.swing.GroupLayout.PREFERRED_SIZE, 686, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(215, Short.MAX_VALUE))
        );
        panelDouvertureLayout.setVerticalGroup(
            panelDouvertureLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelDouvertureLayout.createSequentialGroup()
                .addGap(196, 196, 196)
                .addComponent(jLabel14, javax.swing.GroupLayout.PREFERRED_SIZE, 69, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        DMA.add(panelDouverture, "card3");

        panelOnglets.setBorder(javax.swing.BorderFactory.createTitledBorder(""));

        jLabel5.setText("Nom");

        jLabel6.setText("Prénom");

        jLabel7.setText("IPP");

        jLabel8.setText("Date de naissance");

        jLabel12.setText("Sexe");

        jLabel13.setText("Adresse");

        textFieldNom.setEditable(false);
        textFieldNom.setBackground(new java.awt.Color(204, 204, 204));
        textFieldNom.setText("non edit");
        textFieldNom.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                textFieldNomActionPerformed(evt);
            }
        });

        textFieldPrenom.setEditable(false);
        textFieldPrenom.setBackground(new java.awt.Color(204, 204, 204));
        textFieldPrenom.setText("non edit");

        textFieldSexe.setEditable(false);
        textFieldSexe.setBackground(new java.awt.Color(204, 204, 204));
        textFieldSexe.setText("non edit");

        textFieldIPP.setEditable(false);
        textFieldIPP.setBackground(new java.awt.Color(204, 204, 204));
        textFieldIPP.setText("non edit");

        textFieldDateNaissance.setEditable(false);
        textFieldDateNaissance.setBackground(new java.awt.Color(204, 204, 204));
        textFieldDateNaissance.setText("non edit");

        textFieldAdresse.setEditable(false);
        textFieldAdresse.setBackground(new java.awt.Color(204, 204, 204));
        textFieldAdresse.setText("non edit");

        javax.swing.GroupLayout ongletFichePatientLayout = new javax.swing.GroupLayout(ongletFichePatient);
        ongletFichePatient.setLayout(ongletFichePatientLayout);
        ongletFichePatientLayout.setHorizontalGroup(
            ongletFichePatientLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(ongletFichePatientLayout.createSequentialGroup()
                .addGap(265, 265, 265)
                .addGroup(ongletFichePatientLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel12)
                    .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel8)
                    .addComponent(jLabel13))
                .addGap(33, 33, 33)
                .addGroup(ongletFichePatientLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(textFieldAdresse, javax.swing.GroupLayout.PREFERRED_SIZE, 379, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(ongletFichePatientLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                        .addComponent(textFieldDateNaissance, javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(textFieldPrenom, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 152, Short.MAX_VALUE)
                        .addComponent(textFieldSexe, javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(textFieldIPP, javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(textFieldNom, javax.swing.GroupLayout.Alignment.LEADING)))
                .addContainerGap(337, Short.MAX_VALUE))
        );
        ongletFichePatientLayout.setVerticalGroup(
            ongletFichePatientLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(ongletFichePatientLayout.createSequentialGroup()
                .addGap(120, 120, 120)
                .addGroup(ongletFichePatientLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(textFieldNom, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(ongletFichePatientLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(textFieldPrenom, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(ongletFichePatientLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel12, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(textFieldSexe, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(ongletFichePatientLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel7)
                    .addComponent(textFieldIPP, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(ongletFichePatientLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(textFieldDateNaissance, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(ongletFichePatientLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel13, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(textFieldAdresse, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        panelOnglets.addTab("Fiche du patient", ongletFichePatient);

        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder(""));

        boutonEnregistrer.setText("Enregistrer les modifications");
        boutonEnregistrer.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                boutonEnregistrerActionPerformed(evt);
            }
        });

        boutonModifier.setText("Modifier");
        boutonModifier.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                boutonModifierActionPerformed(evt);
            }
        });

        labelPlacement.setText("Placement");

        comboBoxPlacement.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "porte", "fenetre", "Unique" }));
        comboBoxPlacement.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                comboBoxPlacementActionPerformed(evt);
            }
        });

        champNumeroChambre.setEditable(false);
        champNumeroChambre.setBackground(new java.awt.Color(204, 204, 204));
        champNumeroChambre.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                champNumeroChambreActionPerformed(evt);
            }
        });

        labelNumeroChambre.setText("Numéro de chambre");

        labelService.setText("Service");

        comboBoxService.setModel(new javax.swing.DefaultComboBoxModel(new String[] {}));
        comboBoxService.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                comboBoxServiceActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(29, 29, 29)
                .addComponent(labelNumeroChambre)
                .addGap(32, 32, 32)
                .addComponent(champNumeroChambre, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(119, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(boutonEnregistrer))
            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanel1Layout.createSequentialGroup()
                    .addGap(30, 30, 30)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                        .addComponent(boutonModifier, javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(jPanel1Layout.createSequentialGroup()
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(labelService)
                                .addComponent(labelPlacement))
                            .addGap(79, 79, 79)
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(comboBoxPlacement, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(comboBoxService, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGap(213, 213, 213)))
                    .addContainerGap(27, Short.MAX_VALUE)))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(89, 89, 89)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(labelNumeroChambre)
                    .addComponent(champNumeroChambre, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 120, Short.MAX_VALUE)
                .addComponent(boutonEnregistrer)
                .addGap(25, 25, 25))
            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanel1Layout.createSequentialGroup()
                    .addGap(30, 30, 30)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(labelService)
                        .addComponent(comboBoxService, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGap(105, 105, 105)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(labelPlacement)
                        .addComponent(comboBoxPlacement, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGap(54, 54, 54)
                    .addComponent(boutonModifier)
                    .addContainerGap(25, Short.MAX_VALUE)))
        );

        javax.swing.GroupLayout ongletLocalisationLayout = new javax.swing.GroupLayout(ongletLocalisation);
        ongletLocalisation.setLayout(ongletLocalisationLayout);
        ongletLocalisationLayout.setHorizontalGroup(
            ongletLocalisationLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(ongletLocalisationLayout.createSequentialGroup()
                .addGap(302, 302, 302)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(370, Short.MAX_VALUE))
        );
        ongletLocalisationLayout.setVerticalGroup(
            ongletLocalisationLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, ongletLocalisationLayout.createSequentialGroup()
                .addContainerGap(136, Short.MAX_VALUE)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(120, 120, 120))
        );

        panelOnglets.addTab("Localisation", ongletLocalisation);

        listeSejours.setBorder(javax.swing.BorderFactory.createTitledBorder("Liste de séjours"));
        listeSejours.setModel(new javax.swing.AbstractListModel() {
            String[] strings = { };
            public int getSize() { return strings.length; }
            public Object getElementAt(int i) { return strings[i]; }
        });
        listeSejours.setAutoscrolls(false);
        listeSejours.setMinimumSize(new java.awt.Dimension(300, 0));
        listeSejours.addListSelectionListener(new javax.swing.event.ListSelectionListener() {
            public void valueChanged(javax.swing.event.ListSelectionEvent evt) {
                listeSejoursValueChanged(evt);
            }
        });
        jScrollSejours.setViewportView(listeSejours);

        labelDateEntree.setText("Date d'entrée");

        champJourEntree.setEditable(false);
        champJourEntree.setBackground(new java.awt.Color(204, 204, 204));
        champJourEntree.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                champJourEntreeActionPerformed(evt);
            }
        });

        jLabel1.setText("/");

        champMoisEntree.setEditable(false);
        champMoisEntree.setBackground(new java.awt.Color(204, 204, 204));

        jLabel2.setText("/");

        champAnneeEntree.setEditable(false);
        champAnneeEntree.setBackground(new java.awt.Color(204, 204, 204));

        labelDateSortie.setText("Date de Sortie");

        champJourSortie.setEditable(false);
        champJourSortie.setBackground(new java.awt.Color(204, 204, 204));
        champJourSortie.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                champJourSortieActionPerformed(evt);
            }
        });

        jLabel3.setText("/");

        champMoisSortie.setEditable(false);
        champMoisSortie.setBackground(new java.awt.Color(204, 204, 204));

        jLabel4.setText("/");

        champAnneeSortie.setEditable(false);
        champAnneeSortie.setBackground(new java.awt.Color(204, 204, 204));

        labelNumeroSejour.setText("Numéro de séjour");

        champNumeroSejour.setEditable(false);
        champNumeroSejour.setBackground(new java.awt.Color(204, 204, 204));

        labelPhResponsable.setText("Nom du PH responsable");

        champPhResponsable.setEditable(false);
        champPhResponsable.setBackground(new java.awt.Color(204, 204, 204));
        champPhResponsable.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                champPhResponsableActionPerformed(evt);
            }
        });

        listePrestations.setBorder(javax.swing.BorderFactory.createTitledBorder("Prestations"));
        jScrollPane1.setViewportView(listePrestations);

        javax.swing.GroupLayout panelSejourLayout = new javax.swing.GroupLayout(panelSejour);
        panelSejour.setLayout(panelSejourLayout);
        panelSejourLayout.setHorizontalGroup(
            panelSejourLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelSejourLayout.createSequentialGroup()
                .addGap(30, 30, 30)
                .addGroup(panelSejourLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(panelSejourLayout.createSequentialGroup()
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 600, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(panelSejourLayout.createSequentialGroup()
                        .addGroup(panelSejourLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(panelSejourLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addGroup(panelSejourLayout.createSequentialGroup()
                                    .addGroup(panelSejourLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                        .addComponent(labelDateEntree, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(labelDateSortie, javax.swing.GroupLayout.DEFAULT_SIZE, 79, Short.MAX_VALUE))
                                    .addGap(0, 0, Short.MAX_VALUE))
                                .addGroup(panelSejourLayout.createSequentialGroup()
                                    .addComponent(labelNumeroSejour)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                            .addGroup(panelSejourLayout.createSequentialGroup()
                                .addComponent(labelPhResponsable)
                                .addGap(21, 21, 21)))
                        .addGroup(panelSejourLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(panelSejourLayout.createSequentialGroup()
                                .addComponent(champPhResponsable)
                                .addGap(565, 565, 565))
                            .addGroup(panelSejourLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                .addGroup(panelSejourLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelSejourLayout.createSequentialGroup()
                                        .addComponent(champJourSortie, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(jLabel3)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(champMoisSortie, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(jLabel4)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(champAnneeSortie, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(466, 466, 466))
                                    .addGroup(panelSejourLayout.createSequentialGroup()
                                        .addComponent(champNumeroSejour, javax.swing.GroupLayout.PREFERRED_SIZE, 112, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(480, 480, 480)))
                                .addGroup(panelSejourLayout.createSequentialGroup()
                                    .addComponent(champJourEntree, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addComponent(jLabel1)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addComponent(champMoisEntree, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addComponent(jLabel2)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addComponent(champAnneeEntree, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGap(466, 466, 466)))))))
        );
        panelSejourLayout.setVerticalGroup(
            panelSejourLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelSejourLayout.createSequentialGroup()
                .addGap(19, 19, 19)
                .addGroup(panelSejourLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(labelDateEntree)
                    .addComponent(champJourEntree, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel1)
                    .addComponent(champMoisEntree, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2)
                    .addComponent(champAnneeEntree, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(panelSejourLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(labelDateSortie)
                    .addComponent(champJourSortie, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel3)
                    .addComponent(champMoisSortie, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel4)
                    .addComponent(champAnneeSortie, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(panelSejourLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(labelNumeroSejour)
                    .addComponent(champNumeroSejour, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(panelSejourLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(labelPhResponsable)
                    .addComponent(champPhResponsable, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 223, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(154, Short.MAX_VALUE))
        );

        boutonAjouterSejour.setText("Ajouter un Séjour");
        boutonAjouterSejour.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                boutonAjouterSejourActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout ongletSejourLayout = new javax.swing.GroupLayout(ongletSejour);
        ongletSejour.setLayout(ongletSejourLayout);
        ongletSejourLayout.setHorizontalGroup(
            ongletSejourLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(ongletSejourLayout.createSequentialGroup()
                .addGroup(ongletSejourLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jScrollSejours, javax.swing.GroupLayout.DEFAULT_SIZE, 248, Short.MAX_VALUE)
                    .addComponent(boutonAjouterSejour, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(panelSejour, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        ongletSejourLayout.setVerticalGroup(
            ongletSejourLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(ongletSejourLayout.createSequentialGroup()
                .addGroup(ongletSejourLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(ongletSejourLayout.createSequentialGroup()
                        .addComponent(jScrollSejours, javax.swing.GroupLayout.PREFERRED_SIZE, 420, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(boutonAjouterSejour))
                    .addComponent(panelSejour, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(11, 11, 11))
        );

        panelOnglets.addTab("Séjours", ongletSejour);

        texteLettreSortie.setEditable(false);
        texteLettreSortie.setColumns(20);
        texteLettreSortie.setRows(5);
        texteLettreSortie.setBorder(javax.swing.BorderFactory.createTitledBorder("Lettre de sortie"));
        jScrollPane2.setViewportView(texteLettreSortie);

        boutonFermerDPI.setText("Fermer DPI");
        boutonFermerDPI.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                boutonFermerDPIActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout ongletLettreSortieLayout = new javax.swing.GroupLayout(ongletLettreSortie);
        ongletLettreSortie.setLayout(ongletLettreSortieLayout);
        ongletLettreSortieLayout.setHorizontalGroup(
            ongletLettreSortieLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(ongletLettreSortieLayout.createSequentialGroup()
                .addGap(35, 35, 35)
                .addGroup(ongletLettreSortieLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 690, Short.MAX_VALUE)
                    .addComponent(boutonFermerDPI, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(377, Short.MAX_VALUE))
        );
        ongletLettreSortieLayout.setVerticalGroup(
            ongletLettreSortieLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(ongletLettreSortieLayout.createSequentialGroup()
                .addGap(45, 45, 45)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 354, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(32, 32, 32)
                .addComponent(boutonFermerDPI)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        panelOnglets.addTab("Lettre de sortie", ongletLettreSortie);

        DMA.add(panelOnglets, "card2");
        panelOnglets.getAccessibleContext().setAccessibleName("Fiche du patient");

        boutonOuvrirDPI.setText("Ouvrir DPI");
        boutonOuvrirDPI.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                boutonOuvrirDPIActionPerformed(evt);
            }
        });

        labelFerme.setFont(new java.awt.Font("MingLiU_HKSCS-ExtB", 0, 18)); // NOI18N
        labelFerme.setHorizontalAlignment(javax.swing.SwingConstants.TRAILING);
        labelFerme.setText("Le DPI est fermé");

        javax.swing.GroupLayout panelDPIFermeLayout = new javax.swing.GroupLayout(panelDPIFerme);
        panelDPIFerme.setLayout(panelDPIFermeLayout);
        panelDPIFermeLayout.setHorizontalGroup(
            panelDPIFermeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelDPIFermeLayout.createSequentialGroup()
                .addGap(419, 419, 419)
                .addGroup(panelDPIFermeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(boutonOuvrirDPI, javax.swing.GroupLayout.PREFERRED_SIZE, 160, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(labelFerme))
                .addContainerGap(532, Short.MAX_VALUE))
        );
        panelDPIFermeLayout.setVerticalGroup(
            panelDPIFermeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelDPIFermeLayout.createSequentialGroup()
                .addGap(193, 193, 193)
                .addComponent(labelFerme)
                .addGap(18, 18, 18)
                .addComponent(boutonOuvrirDPI, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(287, Short.MAX_VALUE))
        );

        DMA.add(panelDPIFerme, "card4");

        panelPrincipal.add(DMA, java.awt.BorderLayout.CENTER);

        InterfaceAdministratif.add(panelPrincipal, java.awt.BorderLayout.CENTER);

        getContentPane().add(InterfaceAdministratif);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jTextFieldRechercheActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldRechercheActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextFieldRechercheActionPerformed

    private void boutonAjouterActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_boutonAjouterActionPerformed

        AjoutPatient test = new AjoutPatient(this, true, this);
        test.setVisible(true);
        
    }//GEN-LAST:event_boutonAjouterActionPerformed

    private void champJourEntreeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_champJourEntreeActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_champJourEntreeActionPerformed

    private void textFieldNomActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_textFieldNomActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_textFieldNomActionPerformed

    private void champPhResponsableActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_champPhResponsableActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_champPhResponsableActionPerformed

    private void champNumeroChambreActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_champNumeroChambreActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_champNumeroChambreActionPerformed

    private void boutonModifierActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_boutonModifierActionPerformed

        comboBoxService.setEnabled(true);
        comboBoxService.setBackground(Color.white);
        champNumeroChambre.setEditable(true);
        champNumeroChambre.setBackground(Color.white);
        comboBoxPlacement.setEnabled(true);
        comboBoxPlacement.setBackground(Color.white);

    }//GEN-LAST:event_boutonModifierActionPerformed

    private void comboBoxPlacementActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_comboBoxPlacementActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_comboBoxPlacementActionPerformed

    private void boutonEnregistrerActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_boutonEnregistrerActionPerformed

        if ((champNumeroChambre.getText().equals("") == false) && 
                (pichisNF.fonctions.isNumeric(champNumeroChambre.getText())) && 
                (comboBoxPlacement.getSelectedIndex() != -1 && comboBoxService.getSelectedIndex() != -1)) {
            //patientSelectionne.mettre a jour donnees

            comboBoxService.setEnabled(false);
            comboBoxService.setBackground(Color.LIGHT_GRAY);
            champNumeroChambre.setEditable(false);
            champNumeroChambre.setBackground(Color.LIGHT_GRAY);
            comboBoxPlacement.setEnabled(false);
            comboBoxPlacement.setBackground(Color.LIGHT_GRAY);
            
            Sejour sejourRecent = daoSejour.consulterListeSejourParPatient(modeleListeDPI.get(listeDePatients.getSelectedIndex())).getDernierSejour();
            
            if(sejourRecent != null && comboBoxService.getSelectedIndex() != -1 && champNumeroChambre.getText().isEmpty() == false && comboBoxPlacement.getSelectedIndex() != -1){
                Services s = new Services(TypeServices.CLINIQUE, Specialite.valueOf(comboBoxService.getSelectedItem().toString()));
                daoLoc.changerLocalisationSejour(sejourRecent.getNumeroSejour(), daoService.idParService(s), champNumeroChambre.getText(), comboBoxPlacement.getSelectedItem().toString());
            }
            

        } else {
            JOptionPane.showMessageDialog(null, "Veuillez rentrer un nombre pour le numéro de chambre");
        }

    }//GEN-LAST:event_boutonEnregistrerActionPerformed

    private void listeSejoursValueChanged(javax.swing.event.ListSelectionEvent evt) {//GEN-FIRST:event_listeSejoursValueChanged
            if(listeSejours.getSelectedValue() != null) {
                this.effaceDonneesSejour();
                this.affichageDonneesSejour();
            }
    }//GEN-LAST:event_listeSejoursValueChanged

    private void boutonAjouterSejourActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_boutonAjouterSejourActionPerformed
        AjoutSejour ajoutSejour = new AjoutSejour(modeleListeDPI.get(listeDePatients.getSelectedIndex()), this);
        ajoutSejour.setVisible(true);
    }//GEN-LAST:event_boutonAjouterSejourActionPerformed

    private void jLabel38MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel38MouseClicked
        int confirm = JOptionPane.showConfirmDialog(null, "Êtes vous sûr de vouloir vous déconnecter" + " ?", "Confirmation", JOptionPane.YES_NO_OPTION);

        if (confirm == JOptionPane.YES_OPTION) {
            this.dispose();
            new Identification();
        }


    }//GEN-LAST:event_jLabel38MouseClicked

    private void listeDePatientsValueChanged(javax.swing.event.ListSelectionEvent evt) {//GEN-FIRST:event_listeDePatientsValueChanged
        if(listeDePatients.getSelectedValue() != null) {
            if(daoDpi.getOuvert(modeleListeDPI.get(listeDePatients.getSelectedIndex()).getIpp())){
                CardLayout c = (CardLayout) (DMA.getLayout());
                c.show(DMA, "card2");
            }    
            else{
                CardLayout c = (CardLayout) (DMA.getLayout());
                c.show(DMA, "card4");
            }
                this.affichageDonneesPatient();
            
                this.affichageSejoursDuPatient(modeleListeDPI.get(listeDePatients.getSelectedIndex()));
                this.effaceDonneesSejour();
            
                this.effaceDonneesLocalisation();          
                this.affichageLocalisation();
            
                this.afficherPrestations(modeleListeDPI.get(listeDePatients.getSelectedIndex()));        
        
                this.afficherLettre(modeleListeDPI.get(listeDePatients.getSelectedIndex()));
        }
    }//GEN-LAST:event_listeDePatientsValueChanged

    private void jTextFieldRechercheKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTextFieldRechercheKeyTyped


    }//GEN-LAST:event_jTextFieldRechercheKeyTyped

    private void jTextFieldRechercheInputMethodTextChanged(java.awt.event.InputMethodEvent evt) {//GEN-FIRST:event_jTextFieldRechercheInputMethodTextChanged

    }//GEN-LAST:event_jTextFieldRechercheInputMethodTextChanged

    private void jTextFieldRechercheKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTextFieldRechercheKeyReleased

        if (!jTextFieldRecherche.getText().isEmpty()) {
            ArrayList listeDesPatients = new ArrayList();

            for (int i = 0; i < modeleListeDPI.getSize(); i++) {

                listeDesPatients.add(modeleListeDPI.get(i).getNom());

            }

            ArrayList listeDesPatientsRecherchee = fonctions.recherche(listeDesPatients, jTextFieldRecherche.getText());

            modeleListeDPIRecherche = new DefaultListModel<DPI>();
            for (int i = 0; i < modeleListeDPI.getSize(); i++) {

                for (int j = 0; j < listeDesPatientsRecherchee.size(); j++) {
                    if (listeDesPatientsRecherchee.get(j).equals(modeleListeDPI.get(i).getNom()) && !modeleListeDPIRecherche.contains(modeleListeDPI.elementAt(i))) {
                        modeleListeDPIRecherche.addElement(modeleListeDPI.elementAt(i));
                    }

                }
            }

            listeDePatients.setModel(modeleListeDPIRecherche);
        } else {
            listeDePatients.setModel(modeleListeDPI);
        }
    }//GEN-LAST:event_jTextFieldRechercheKeyReleased

    private void comboBoxServiceActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_comboBoxServiceActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_comboBoxServiceActionPerformed

    private void boutonFermerDPIActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_boutonFermerDPIActionPerformed
        DPI patient = modeleListeDPI.get(listeDePatients.getSelectedIndex());
        Sejour sejour = daoSejour.consulterListeSejourParPatient(patient).getDernierSejour();
        if(sejour != null){
            if(daoSejour.lettreDeSortie(sejour.getNumeroSejour())){
            
                CardLayout c = (CardLayout) (DMA.getLayout());
                c.show(DMA, "card4");
                daoDpi.fermerDPI(modeleListeDPI.get(listeDePatients.getSelectedIndex()).getIpp());
                daoSejour.ajoutDateSortie(sejour.getNumeroSejour());
            }    
            else{
                JOptionPane.showMessageDialog(null, "Aucune lettre de sortie presente", "Fermeture DPI", JOptionPane.INFORMATION_MESSAGE);
            }
        }
        else{
            JOptionPane.showMessageDialog(null, "Aucune lettre de sortie presente", "Fermeture DPI", JOptionPane.INFORMATION_MESSAGE);
        }
    }//GEN-LAST:event_boutonFermerDPIActionPerformed

    private void boutonOuvrirDPIActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_boutonOuvrirDPIActionPerformed
        CardLayout c = (CardLayout) (DMA.getLayout());
        c.show(DMA, "card2");
        daoDpi.ouvrirDPI(modeleListeDPI.get(listeDePatients.getSelectedIndex()).getIpp());
        if(listeSejours.getSelectedValue() != null && listeDePatients.getSelectedValue() != null) {
                this.affichageDonneesPatient();
            
                this.affichageSejoursDuPatient(modeleListeDPI.get(listeDePatients.getSelectedIndex()));
                this.effaceDonneesSejour();
            
                this.effaceDonneesLocalisation();          
                this.affichageLocalisation();
            
                this.afficherPrestations(modeleListeDPI.get(listeDePatients.getSelectedIndex()));        
        
                this.afficherLettre(modeleListeDPI.get(listeDePatients.getSelectedIndex()));
            }
    }//GEN-LAST:event_boutonOuvrirDPIActionPerformed

    private void champJourSortieActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_champJourSortieActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_champJourSortieActionPerformed

    public void miseAJour() {
        /**
         * Méthode assurant la mise à jour de la liste des patients de
         * l'établissement
         */
        daoDpi = new pichisBD.DAODPI();

        modeleListeDPI.clear();
        for (int i = 0; i < daoDpi.consulterListeDPI().size(); i++) {

            modeleListeDPI.addElement(daoDpi.consulterListeDPI().get(i));

        }
        listeDePatients.setModel(modeleListeDPI);
    }
    
    public void affichageDonneesPatient() {
        /**
         * Méthode actualisant l'affichant des données d'un patient sur
         * l'interface
         */
        if (listeDePatients.getModel().getSize() != 0 && listeDePatients.getSelectedIndex() >= 0) {

            DefaultListModel<pichisNF.DPI> modele = (DefaultListModel<pichisNF.DPI>) listeDePatients.getModel();

            int indice = listeDePatients.getSelectedIndex();

            textFieldNom.setText(modele.get(indice).getNom());
            textFieldPrenom.setText(modele.get(indice).getPrenom());
            textFieldSexe.setText(modele.get(indice).getSexe());
            textFieldIPP.setText(modele.get(indice).getIpp());
            textFieldDateNaissance.setText(modele.get(indice).getDateNaissance().toString());
            textFieldAdresse.setText(modele.get(indice).getAdresse());

        }
    }
    
    public void affichageDonneesSejour(){      
        if (listeSejours.getModel().getSize() != 0 && listeSejours.getSelectedIndex() >= 0) {
            DefaultListModel<Sejour> modele = (DefaultListModel<Sejour>) listeSejours.getModel();
            
            int indice = listeSejours.getSelectedIndex();
            Sejour sejourActuel = modele.get(indice);
            
            champJourEntree.setText(sejourActuel.getDateEntree().getJour());
            champMoisEntree.setText(sejourActuel.getDateEntree().getMois());
            champAnneeEntree.setText(sejourActuel.getDateEntree().getAnnee());
            
            champNumeroSejour.setText(sejourActuel.getNumeroSejour());
           
            champPhResponsable.setText(sejourActuel.getPHResponsable().toString());
            
            if(sejourActuel.getDateSortie() != null){             
                champJourSortie.setText(sejourActuel.getDateSortie().getJour());
                champMoisSortie.setText(sejourActuel.getDateSortie().getMois());
                champAnneeSortie.setText(sejourActuel.getDateSortie().getAnnee());
            }
            
            this.affichageLocalisation();
        }
    }
    
    public void effaceDonneesSejour(){
          champJourEntree.setText("");
          champMoisEntree.setText("");
          champAnneeEntree.setText(""); 
          champJourSortie.setText("");
          champMoisSortie.setText("");
          champAnneeSortie.setText("");
          champNumeroSejour.setText("");
          champPhResponsable.setText("");
          
    }
    
    public void affichageSejoursDuPatient(DPI dpi){
        ArrayList<Sejour> listeSejoursTemp = new ArrayList<Sejour>();
        modeleListeSejour.clear();

        listeSejoursTemp = daoSejour.consulterListeSejourParPatient(dpi).getListeSejours();
        
            for(int j=0; j<listeSejoursTemp.size(); j++){
                modeleListeSejour.addElement(listeSejoursTemp.get(j));
            }
        listeSejours.setModel(modeleListeSejour);     
    }
    
    public void affichageListeDePatients(){    
        ArrayList<DPI> listeDPITemp = new ArrayList<DPI>();
        listeDPITemp = daoDpi.consulterListeDPI();
        
        modeleListeDPI.clear();
        for (int i = 0; i < listeDPITemp.size(); i++) {  
            modeleListeDPI.addElement(listeDPITemp.get(i));
        }
        listeDePatients.setModel(modeleListeDPI);       
    }
    
    public void affichageLocalisation(){
        Sejour sejourRecent;
        Localisation loc;       
        
        sejourRecent = daoSejour.consulterListeSejourParPatient(modeleListeDPI.get(listeDePatients.getSelectedIndex())).getDernierSejour();
        
        if(sejourRecent != null){        
            loc = daoLoc.localisationParNumeroDeSejour(sejourRecent.getNumeroSejour());
                      
            comboBoxService.setSelectedItem(loc.getService().getSpecialite());
            champNumeroChambre.setText(loc.getNumeroChambre());
            comboBoxPlacement.setSelectedItem(loc.getPlacement());
        }
    }
    
    public void effaceDonneesLocalisation(){
        comboBoxPlacement.setSelectedIndex(-1);
        champNumeroChambre.setText("");
        comboBoxService.setSelectedIndex(-1);
    }
    
    public void afficherPrestations(DPI dpi){
        ArrayList<Prestations> listePrestationsTemp = new ArrayList<Prestations>();
        listePrestationsTemp = daoPrestations.prestationsPatient(dpi.getIpp());
        
        modeleListePrestation.clear();
        for (int i = 0; i < listePrestationsTemp.size(); i++) {  
            modeleListePrestation.addElement(listePrestationsTemp.get(i));
        }
        
        listePrestations.setModel(modeleListePrestation);
    }
    
    public void afficherLettre(DPI dpi){
        Sejour sejourActuel = daoSejour.consulterListeSejourParPatient(dpi).getDernierSejour();
        if(daoSejour.lettreDeSortie(sejourActuel.getNumeroSejour())){
            String txt = "Je soussigné docteur " + sejourActuel.getPHResponsable().toString() + ", médecin responsable du séjour du patient : " + dpi.getNom() + " " + dpi.getPrenom() + "\n" + " édite en ce jour sa lettre de sortie." + "\n\n" + "Date :" + pichisNF.fonctions.renvoieDateActuelle();
            texteLettreSortie.setText(txt);
        }
        else{
            texteLettreSortie.setText("");
        }
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel DMA;
    private javax.swing.JPanel InterfaceAdministratif;
    private javax.swing.JLabel LabelBoutonRecherche;
    private javax.swing.JPanel PanelBarreTitre;
    private javax.swing.JButton boutonAjouter;
    private javax.swing.JButton boutonAjouterSejour;
    private javax.swing.JButton boutonEnregistrer;
    private javax.swing.JButton boutonFermerDPI;
    private javax.swing.JButton boutonModifier;
    private javax.swing.JButton boutonOuvrirDPI;
    private javax.swing.JTextField champAnneeEntree;
    private javax.swing.JTextField champAnneeSortie;
    private javax.swing.JTextField champJourEntree;
    private javax.swing.JTextField champJourSortie;
    private javax.swing.JTextField champMoisEntree;
    private javax.swing.JTextField champMoisSortie;
    private javax.swing.JTextField champNumeroChambre;
    private javax.swing.JTextField champNumeroSejour;
    private javax.swing.JTextField champPhResponsable;
    private javax.swing.JComboBox comboBoxPlacement;
    private javax.swing.JComboBox comboBoxService;
    private javax.swing.JLabel image;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel37;
    private javax.swing.JLabel jLabel38;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollSejours;
    private javax.swing.JTextField jTextFieldRecherche;
    private javax.swing.JLabel labelDateEntree;
    private javax.swing.JLabel labelDateSortie;
    private javax.swing.JLabel labelFerme;
    private javax.swing.JLabel labelNumeroChambre;
    private javax.swing.JLabel labelNumeroSejour;
    private javax.swing.JLabel labelPhResponsable;
    private javax.swing.JLabel labelPlacement;
    private javax.swing.JLabel labelRecherche;
    private javax.swing.JLabel labelService;
    private javax.swing.JList listeDePatients;
    private javax.swing.JList listePrestations;
    private javax.swing.JList listeSejours;
    private javax.swing.JPanel ongletFichePatient;
    private javax.swing.JPanel ongletLettreSortie;
    private javax.swing.JPanel ongletLocalisation;
    private javax.swing.JPanel ongletSejour;
    private javax.swing.JPanel panelBarreRecherche;
    private javax.swing.JPanel panelDPIFerme;
    private javax.swing.JPanel panelDouverture;
    private javax.swing.JPanel panelListe;
    private javax.swing.JTabbedPane panelOnglets;
    private javax.swing.JPanel panelPrincipal;
    private javax.swing.JPanel panelSejour;
    private javax.swing.JPanel panelTitre;
    private javax.swing.JScrollPane scrollPaneListePatient;
    private javax.swing.JTextField textFieldAdresse;
    private javax.swing.JTextField textFieldDateNaissance;
    private javax.swing.JTextField textFieldIPP;
    private javax.swing.JTextField textFieldNom;
    private javax.swing.JTextField textFieldPrenom;
    private javax.swing.JTextField textFieldSexe;
    private javax.swing.JTextArea texteLettreSortie;
    // End of variables declaration//GEN-END:variables
}
