/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package pichisUI;

import java.awt.CardLayout;
import java.awt.GraphicsEnvironment;
import java.awt.Rectangle;
import java.text.DateFormat;
import java.text.SimpleDateFormat;
import java.util.ArrayList;
import java.util.Calendar;
import java.util.Date;
import javax.swing.DefaultListModel;
import javax.swing.JFrame;
import javax.swing.JOptionPane;
import pichisBD.DAOObservation;
import pichisBD.DAOPrestations;
import pichisBD.DAOResultat;
import pichisNF.Medecin;
import pichisNF.Observation;
import pichisNF.Prestations;

/**
 *
 * @author Johann
 */
public class InterfaceServiceMedicoTechnique extends javax.swing.JFrame {

    /**
     * Creates new form InterfaceServiceMedicoTechnique
     */
    private DefaultListModel<pichisNF.Prestations> modeleListePrestations;
    private Medecin m;
    private GraphicsEnvironment graphicsEnvironment = GraphicsEnvironment.getLocalGraphicsEnvironment();
    private Rectangle maximumWindowBounds = graphicsEnvironment.getMaximumWindowBounds();
    private int width = (int) (maximumWindowBounds.width - 0.015 * maximumWindowBounds.width);
    private int height = (int) (maximumWindowBounds.height - 0.02 * maximumWindowBounds.height);

    public InterfaceServiceMedicoTechnique(Medecin m) {
        this.m = m;

        setSize(maximumWindowBounds.width, maximumWindowBounds.height);
        initComponents();

        DAOPrestations daoPrestations = new pichisBD.DAOPrestations();
        //Définit un titre pour notre fenêtre
        setTitle("PICHIS Service Médico-Technique");
        //Définit sa taille : 400 pixels de large et 100 pixels de haut
        //setSize(1365, 765);
        //this.setResizable(false);
        //Nous demandons maintenant à notre objet de se positionner au centre
        setLocationRelativeTo(null);
        //Termine le processus lorsqu'on clique sur la croix rouge
        setDefaultCloseOperation(JFrame.DISPOSE_ON_CLOSE);
//        this.pack();
//        this.setDefaultLookAndFeelDecorated(true);
//        this.setExtendedState(this.MAXIMIZED_BOTH);

        //Remplissage de la liste des prestations demandées
        modeleListePrestations = new DefaultListModel<pichisNF.Prestations>();

        for (int i = 0; i < daoPrestations.consulterListePrestationsNonRealisee().size(); i++) {
            modeleListePrestations.addElement(daoPrestations.consulterListePrestationsNonRealisee2().get(i));
        }
        listePrestations.setModel(modeleListePrestations);

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        InterfaceServiceMedicoTechnique = new javax.swing.JPanel();
        jPanel12 = new javax.swing.JPanel();
        jPanel13 = new javax.swing.JPanel();
        jLabel31 = new javax.swing.JLabel();
        jLabel32 = new javax.swing.JLabel();
        jLabel33 = new javax.swing.JLabel();
        jLabel34 = new javax.swing.JLabel();
        jLabel37 = new javax.swing.JLabel();
        jLabel38 = new javax.swing.JLabel();
        jPanel14 = new javax.swing.JPanel();
        jLabel39 = new javax.swing.JLabel();
        jTextField3 = new javax.swing.JTextField();
        jLabel40 = new javax.swing.JLabel();
        jPanel7 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        listePrestations = new javax.swing.JList();
        jPanel8 = new javax.swing.JPanel();
        panelDouverture = new javax.swing.JPanel();
        jLabel15 = new javax.swing.JLabel();
        jTabbedPane1 = new javax.swing.JTabbedPane();
        jPanel1 = new javax.swing.JPanel();
        jPanel5 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jTextFieldAdresse = new javax.swing.JTextField();
        jTextFieldDateNaissance = new javax.swing.JTextField();
        jTextFieldIPP = new javax.swing.JTextField();
        jTextFieldSexe = new javax.swing.JTextField();
        jTextFieldPrenom = new javax.swing.JTextField();
        jTextFieldNom = new javax.swing.JTextField();
        jPanel3 = new javax.swing.JPanel();
        jScrollPane2 = new javax.swing.JScrollPane();
        listeObservations = new javax.swing.JList();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jTextFieldPHObservation = new javax.swing.JTextField();
        jScrollPane3 = new javax.swing.JScrollPane();
        jTextAreaDescription = new javax.swing.JTextArea();
        jTextFieldDateObservation = new javax.swing.JTextField();
        jPanel4 = new javax.swing.JPanel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        jScrollPane4 = new javax.swing.JScrollPane();
        jTextPaneAjoutResultat = new javax.swing.JTextPane();
        jButton1 = new javax.swing.JButton();
        jTextFieldIPP2 = new javax.swing.JTextField();
        jTextFieldNaturePrestation = new javax.swing.JTextField();
        jTextFieldPH = new javax.swing.JTextField();
        jTextFieldDateDemande = new javax.swing.JTextField();
        jFormattedTextFieldDateRealisation = new javax.swing.JFormattedTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        InterfaceServiceMedicoTechnique.setBackground(new java.awt.Color(229, 229, 229));
        InterfaceServiceMedicoTechnique.setMaximumSize(new java.awt.Dimension(1600, 500));
        InterfaceServiceMedicoTechnique.setPreferredSize(new java.awt.Dimension(width, height));
        InterfaceServiceMedicoTechnique.setLayout(new java.awt.BorderLayout());

        jPanel12.setLayout(new java.awt.BorderLayout());

        jPanel13.setBackground(new java.awt.Color(255, 255, 255));
        jPanel13.setPreferredSize(new java.awt.Dimension(1550, 165));

        jLabel31.setIcon(new javax.swing.ImageIcon(getClass().getResource("/data/Images/noun_59269_cc.png"))); // NOI18N

        jLabel32.setFont(new java.awt.Font("Garamond", 0, 24)); // NOI18N
        jLabel32.setText(m.getNom());

        jLabel33.setFont(new java.awt.Font("Garamond", 0, 36)); // NOI18N
        jLabel33.setText(m.getNom());

        jLabel34.setFont(new java.awt.Font("Trajan Pro", 0, 37)); // NOI18N
        jLabel34.setText("Service Médico-Technique");

        jLabel37.setIcon(new javax.swing.ImageIcon(getClass().getResource("/data/Images/iconmonstr-wrench-20-icon-64.png"))); // NOI18N
        jLabel37.setText("Préférences");
        jLabel37.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jLabel37.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jLabel37.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);

        jLabel38.setIcon(new javax.swing.ImageIcon(getClass().getResource("/data/Images/iconmonstr-logout-3-icon-64.png"))); // NOI18N
        jLabel38.setText("Déconnexion");
        jLabel38.setVerticalAlignment(javax.swing.SwingConstants.TOP);
        jLabel38.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jLabel38.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jLabel38.setIconTextGap(0);
        jLabel38.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        jLabel38.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel38MouseClicked(evt);
            }
        });

        javax.swing.GroupLayout jPanel13Layout = new javax.swing.GroupLayout(jPanel13);
        jPanel13.setLayout(jPanel13Layout);
        jPanel13Layout.setHorizontalGroup(
            jPanel13Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel13Layout.createSequentialGroup()
                .addComponent(jLabel31)
                .addGroup(jPanel13Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel13Layout.createSequentialGroup()
                        .addGap(27, 27, 27)
                        .addGroup(jPanel13Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel33, javax.swing.GroupLayout.PREFERRED_SIZE, 271, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel32, javax.swing.GroupLayout.PREFERRED_SIZE, 271, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(jPanel13Layout.createSequentialGroup()
                        .addGap(24, 24, 24)
                        .addComponent(jLabel34, javax.swing.GroupLayout.PREFERRED_SIZE, 569, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel37)
                .addGap(86, 86, 86)
                .addComponent(jLabel38)
                .addGap(38, 38, 38))
        );
        jPanel13Layout.setVerticalGroup(
            jPanel13Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel13Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel13Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel13Layout.createSequentialGroup()
                        .addComponent(jLabel33, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, 0)
                        .addComponent(jLabel32)
                        .addGap(0, 0, 0)
                        .addComponent(jLabel34))
                    .addGroup(jPanel13Layout.createSequentialGroup()
                        .addGap(23, 23, 23)
                        .addGroup(jPanel13Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel38)
                            .addComponent(jLabel37))))
                .addGap(34, 34, 34))
            .addComponent(jLabel31, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
        );

        jPanel12.add(jPanel13, java.awt.BorderLayout.PAGE_START);

        jPanel14.setBackground(new java.awt.Color(230, 230, 230));
        jPanel14.setBorder(javax.swing.BorderFactory.createTitledBorder(""));
        jPanel14.setPreferredSize(new java.awt.Dimension(1550, 60));
        jPanel14.setLayout(new javax.swing.BoxLayout(jPanel14, javax.swing.BoxLayout.LINE_AXIS));

        jLabel39.setFont(new java.awt.Font("Garamond", 1, 14)); // NOI18N
        jLabel39.setText("Rechercher un patient :");
        jLabel39.setPreferredSize(new java.awt.Dimension(145, 50));
        jPanel14.add(jLabel39);

        jTextField3.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createTitledBorder("")));
        jPanel14.add(jTextField3);

        jLabel40.setIcon(new javax.swing.ImageIcon(getClass().getResource("/data/Images/iconmonstr-magnifier-5-icon-32.png"))); // NOI18N
        jPanel14.add(jLabel40);

        jPanel12.add(jPanel14, java.awt.BorderLayout.PAGE_END);

        InterfaceServiceMedicoTechnique.add(jPanel12, java.awt.BorderLayout.PAGE_START);

        jPanel7.setLayout(new java.awt.BorderLayout());

        listePrestations.setBackground(new java.awt.Color(204, 204, 204));
        listePrestations.setBorder(javax.swing.BorderFactory.createTitledBorder("Prestations demandées"));
        listePrestations.setFont(new java.awt.Font("SimHei", 0, 18)); // NOI18N
        listePrestations.addListSelectionListener(new javax.swing.event.ListSelectionListener() {
            public void valueChanged(javax.swing.event.ListSelectionEvent evt) {
                listePrestationsValueChanged(evt);
            }
        });
        jScrollPane1.setViewportView(listePrestations);

        jPanel7.add(jScrollPane1, java.awt.BorderLayout.WEST);

        jPanel8.setLayout(new java.awt.CardLayout());

        jLabel15.setFont(new java.awt.Font("MingLiU_HKSCS-ExtB", 0, 18)); // NOI18N
        jLabel15.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel15.setText("Sélectionner une prestation");

        javax.swing.GroupLayout panelDouvertureLayout = new javax.swing.GroupLayout(panelDouverture);
        panelDouverture.setLayout(panelDouvertureLayout);
        panelDouvertureLayout.setHorizontalGroup(
            panelDouvertureLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelDouvertureLayout.createSequentialGroup()
                .addGap(210, 210, 210)
                .addComponent(jLabel15, javax.swing.GroupLayout.PREFERRED_SIZE, 686, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        panelDouvertureLayout.setVerticalGroup(
            panelDouvertureLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelDouvertureLayout.createSequentialGroup()
                .addGap(196, 196, 196)
                .addComponent(jLabel15, javax.swing.GroupLayout.PREFERRED_SIZE, 69, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanel8.add(panelDouverture, "card3");

        jTabbedPane1.setBorder(javax.swing.BorderFactory.createTitledBorder(""));

        jPanel5.setBorder(javax.swing.BorderFactory.createTitledBorder(""));

        jLabel1.setText("Nom");

        jLabel2.setText("Prénom");

        jLabel5.setText("Sexe");

        jLabel3.setText("IPP");

        jLabel4.setText("Date de naissance");

        jLabel6.setText("Adresse");

        jTextFieldAdresse.setEditable(false);
        jTextFieldAdresse.setBackground(new java.awt.Color(204, 204, 204));

        jTextFieldDateNaissance.setEditable(false);
        jTextFieldDateNaissance.setBackground(new java.awt.Color(204, 204, 204));

        jTextFieldIPP.setEditable(false);
        jTextFieldIPP.setBackground(new java.awt.Color(204, 204, 204));

        jTextFieldSexe.setEditable(false);
        jTextFieldSexe.setBackground(new java.awt.Color(204, 204, 204));
        jTextFieldSexe.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextFieldSexeActionPerformed(evt);
            }
        });

        jTextFieldPrenom.setEditable(false);
        jTextFieldPrenom.setBackground(new java.awt.Color(204, 204, 204));

        jTextFieldNom.setEditable(false);
        jTextFieldNom.setBackground(new java.awt.Color(204, 204, 204));
        jTextFieldNom.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextFieldNomActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addGap(52, 52, 52)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel5)
                    .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel4)
                    .addComponent(jLabel6))
                .addGap(33, 33, 33)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jTextFieldAdresse, javax.swing.GroupLayout.PREFERRED_SIZE, 311, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                        .addComponent(jTextFieldNom, javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(jTextFieldPrenom, javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(jTextFieldSexe, javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(jTextFieldIPP, javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(jTextFieldDateNaissance, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 152, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(34, Short.MAX_VALUE))
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel5Layout.createSequentialGroup()
                .addContainerGap(41, Short.MAX_VALUE)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTextFieldNom, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTextFieldPrenom, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(26, 26, 26)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTextFieldSexe, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(jTextFieldIPP, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTextFieldDateNaissance, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTextFieldAdresse, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(29, 29, 29))
        );

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(167, 167, 167)
                .addComponent(jPanel5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(64, 64, 64)
                .addComponent(jPanel5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jTabbedPane1.addTab("Fiche du patient", jPanel1);

        jScrollPane2.setName("Liste des observations"); // NOI18N

        listeObservations.addListSelectionListener(new javax.swing.event.ListSelectionListener() {
            public void valueChanged(javax.swing.event.ListSelectionEvent evt) {
                listeObservationsValueChanged(evt);
            }
        });
        jScrollPane2.setViewportView(listeObservations);

        jLabel7.setText("Date");

        jLabel8.setText("Médecin");

        jTextFieldPHObservation.setEditable(false);
        jTextFieldPHObservation.setBackground(new java.awt.Color(204, 204, 204));
        jTextFieldPHObservation.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextFieldPHObservationActionPerformed(evt);
            }
        });

        jTextAreaDescription.setEditable(false);
        jTextAreaDescription.setBackground(new java.awt.Color(204, 204, 204));
        jTextAreaDescription.setColumns(20);
        jTextAreaDescription.setRows(5);
        jTextAreaDescription.setBorder(javax.swing.BorderFactory.createTitledBorder("Descriptions"));
        jScrollPane3.setViewportView(jTextAreaDescription);

        jTextFieldDateObservation.setEditable(false);
        jTextFieldDateObservation.setBackground(new java.awt.Color(204, 204, 204));
        jTextFieldDateObservation.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextFieldDateObservationActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 223, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(112, 112, 112)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                                .addComponent(jLabel7)
                                .addGap(54, 54, 54))
                            .addGroup(jPanel3Layout.createSequentialGroup()
                                .addComponent(jLabel8)
                                .addGap(38, 38, 38)))
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jTextFieldPHObservation)
                            .addComponent(jTextFieldDateObservation, javax.swing.GroupLayout.PREFERRED_SIZE, 136, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 470, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(44, 44, 44)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 386, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGap(19, 19, 19)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel7)
                            .addComponent(jTextFieldDateObservation, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(23, 23, 23)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel8)
                            .addComponent(jTextFieldPHObservation, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 238, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jTabbedPane1.addTab("Observations", jPanel3);

        jLabel10.setText("Patient");

        jLabel11.setText("Nature de la prestation");

        jLabel12.setText("Demandeur");

        jLabel13.setText("Date de la demande");

        jLabel14.setText("Date de réalisation");

        jScrollPane4.setViewportView(jTextPaneAjoutResultat);

        jButton1.setText("Ajouter au dossier médical");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jTextFieldIPP2.setEditable(false);
        jTextFieldIPP2.setBackground(new java.awt.Color(204, 204, 204));
        jTextFieldIPP2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextFieldIPP2ActionPerformed(evt);
            }
        });

        jTextFieldNaturePrestation.setEditable(false);
        jTextFieldNaturePrestation.setBackground(new java.awt.Color(204, 204, 204));

        jTextFieldPH.setEditable(false);
        jTextFieldPH.setBackground(new java.awt.Color(204, 204, 204));

        jTextFieldDateDemande.setEditable(false);
        jTextFieldDateDemande.setBackground(new java.awt.Color(204, 204, 204));

        DateFormat df1 = new SimpleDateFormat("dd-MM-YYYY à HH:mm");
        Date today1 = Calendar.getInstance().getTime();
        String date = df1.format(today1);
        jFormattedTextFieldDateRealisation .setText(date);
        jFormattedTextFieldDateRealisation.setEditable(false);
        jFormattedTextFieldDateRealisation.setBackground(new java.awt.Color(204, 204, 204));

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGap(91, 91, 91)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jButton1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel10)
                            .addComponent(jLabel11)
                            .addComponent(jLabel12)
                            .addComponent(jLabel13)
                            .addComponent(jLabel14))
                        .addGap(45, 45, 45)
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jTextFieldIPP2)
                            .addComponent(jTextFieldNaturePrestation)
                            .addComponent(jTextFieldPH)
                            .addComponent(jTextFieldDateDemande)
                            .addComponent(jFormattedTextFieldDateRealisation, javax.swing.GroupLayout.PREFERRED_SIZE, 155, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(42, 42, 42)
                        .addComponent(jScrollPane4, javax.swing.GroupLayout.PREFERRED_SIZE, 379, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGap(60, 60, 60)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane4, javax.swing.GroupLayout.PREFERRED_SIZE, 250, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel10)
                            .addComponent(jTextFieldIPP2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(26, 26, 26)
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel11)
                            .addComponent(jTextFieldNaturePrestation, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(26, 26, 26)
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel12)
                            .addComponent(jTextFieldPH, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(26, 26, 26)
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel13)
                            .addComponent(jTextFieldDateDemande, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(26, 26, 26)
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel14)
                            .addComponent(jFormattedTextFieldDateRealisation, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addGap(18, 18, 18)
                .addComponent(jButton1)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jTabbedPane1.addTab("Résultats de la prestation demandée", jPanel4);

        jPanel8.add(jTabbedPane1, "card4");

        jPanel7.add(jPanel8, java.awt.BorderLayout.CENTER);

        InterfaceServiceMedicoTechnique.add(jPanel7, java.awt.BorderLayout.CENTER);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 1559, Short.MAX_VALUE)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(InterfaceServiceMedicoTechnique, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 0, Short.MAX_VALUE)))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 910, Short.MAX_VALUE)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(InterfaceServiceMedicoTechnique, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 0, Short.MAX_VALUE)))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jTextFieldNomActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldNomActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextFieldNomActionPerformed

    private void jTextFieldPHObservationActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldPHObservationActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextFieldPHObservationActionPerformed

    private void jTextFieldDateObservationActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldDateObservationActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextFieldDateObservationActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        JOptionPane fenetre = new JOptionPane();
        if (listePrestations.isSelectionEmpty() == true) {
            fenetre.showMessageDialog(null, "Veuillez sélectionner une prestation avant d'ajouter des résultats.");
        } else {
            if (jTextPaneAjoutResultat.isEditable()) {
                if (jTextPaneAjoutResultat.getText().isEmpty()) {
                    fenetre.showMessageDialog(null, "Veuillez saisir les résultats de la prestation demandée avant de pouvoir les ajouter au dossier médical du patient.");
                } else {
                    String[] buttons = {"Oui", "Non"};
                    int reply = JOptionPane.showOptionDialog(null, "Voulez-vous confirmer l'ajout de ces résultats au dossier médical ? ", "Confirmation", JOptionPane.WARNING_MESSAGE, 0, null, buttons, buttons[1]);

                    if (reply == 0) {
                        fenetre.showMessageDialog(null, "Les résultats ont été ajoutés avec succès ! ", "Information", JOptionPane.INFORMATION_MESSAGE);
                        Prestations p1 = (Prestations) listePrestations.getSelectedValue();
                        DAOPrestations daop = new DAOPrestations();

                        DAOResultat daoResultat = new DAOResultat();
                        String idResultat = pichisNF.fonctions.genererIdResultat();
                        daoResultat.ajoutResultat(jFormattedTextFieldDateRealisation.getText(), jTextPaneAjoutResultat.getText(), m.getId(), p1.getIdPrestation(), idResultat);
                        daop.setResultat(p1.getIdPrestation(), idResultat);
                        jTextPaneAjoutResultat.setEnabled(false);
                        modeleListePrestations.remove(listePrestations.getSelectedIndex());
                        listePrestations.setModel(modeleListePrestations);

                        CardLayout c = (CardLayout) (jPanel8.getLayout());
                        c.show(jPanel8, "card3");
                    }
                }
            } else {
                fenetre.showMessageDialog(null, "Les résultats ont déjà été soumis ! ", "Information", JOptionPane.INFORMATION_MESSAGE);
            }
        }
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jTextFieldIPP2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldIPP2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextFieldIPP2ActionPerformed

    private void jLabel38MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel38MouseClicked
        this.dispose();
        new Identification();
    }//GEN-LAST:event_jLabel38MouseClicked

    private void listePrestationsValueChanged(javax.swing.event.ListSelectionEvent evt) {//GEN-FIRST:event_listePrestationsValueChanged
        if (listePrestations.getSelectedValue() != null) {
            this.affichageDonneesPatient();
            this.affichageRésultat();
            this.affichageObservations();

            CardLayout c = (CardLayout) (jPanel8.getLayout());
            c.show(jPanel8, "card4");

        }
    }//GEN-LAST:event_listePrestationsValueChanged

    private void jTextFieldSexeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldSexeActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextFieldSexeActionPerformed

    private void listeObservationsValueChanged(javax.swing.event.ListSelectionEvent evt) {//GEN-FIRST:event_listeObservationsValueChanged

        if (listeObservations.getSelectedValue() != null) {
            Observation o = (Observation) listeObservations.getSelectedValue();
            jTextFieldDateObservation.setText(o.getDate().toString());
            jTextFieldPHObservation.setText(o.getMedecin().getPrenom() + " " + o.getMedecin().getNom());
            jTextAreaDescription.setText(o.getDescription());
        } else {
            jTextFieldDateObservation.setText("");
            jTextFieldPHObservation.setText("");
            jTextAreaDescription.setText("");
        }
    }//GEN-LAST:event_listeObservationsValueChanged

    private void affichageDonneesPatient() {
        /**
         * Méthode actualisant l'affichant des données d'un patient sur
         * l'interface
         */
        if (listePrestations.getModel().getSize() != 0 && listePrestations.getSelectedIndex() >= 0) {

            Prestations p1 = (Prestations) listePrestations.getSelectedValue();

            jTextFieldNom.setText(p1.getPatient().getIpp());
            jTextFieldPrenom.setText(p1.getPatient().getPrenom());
            jTextFieldSexe.setText(p1.getPatient().getSexe());
            jTextFieldIPP.setText(p1.getPatient().getIpp());
            jTextFieldDateNaissance.setText(p1.getPatient().getDateNaissance().toString());
            jTextFieldAdresse.setText(p1.getPatient().getAdresse());
        }
    }

    private void affichageRésultat() {
        /**
         * Méthode actualisant l'affichant des données dans l'onglet "Résultats
         * de la prestation demandée"
         */
        if (listePrestations.getModel().getSize() != 0 && listePrestations.getSelectedIndex() >= 0) {
            Prestations p1 = (Prestations) listePrestations.getSelectedValue();

            jTextFieldIPP2.setText(p1.getPatient().getIpp());
            jTextFieldNaturePrestation.setText(p1.getNaturePrestation());
            jTextFieldPH.setText(p1.getDemandeur().getPrenom() + " " + p1.getDemandeur().getNom());
            jTextFieldDateDemande.setText(p1.getDate().toString());

            System.out.println(p1.getResultat());

            if (p1.getResultat() != null) {
                jTextPaneAjoutResultat.setText(p1.getResultat().getDescriptions());
            } else {
                jTextPaneAjoutResultat.setEditable(true);
                jTextPaneAjoutResultat.setEnabled(true);
                jTextPaneAjoutResultat.setText("");
            }
        }
    }

    /**
     * Remplissage de la liste des observations pour un patient
     */
    public void affichageObservations() {

        if (listePrestations.getModel().getSize() != 0 && listePrestations.getSelectedIndex() >= 0) {
            Prestations p1 = (Prestations) listePrestations.getSelectedValue();
            DAOObservation daoObservations = new DAOObservation();

            ArrayList<Observation> listeObservations2 = daoObservations.observationsPatient(p1.getPatient().getIpp());
            DefaultListModel<Observation> modeleListeObservations = new DefaultListModel<pichisNF.Observation>();
            for (int i = 0; i < listeObservations2.size(); i++) {
                modeleListeObservations.addElement(listeObservations2.get(i));
            }
            listeObservations.setModel(modeleListeObservations);
        }
    }

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(InterfaceServiceMedicoTechnique.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(InterfaceServiceMedicoTechnique.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(InterfaceServiceMedicoTechnique.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(InterfaceServiceMedicoTechnique.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
//                new InterfaceServiceMedicoTechnique().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel InterfaceServiceMedicoTechnique;
    private javax.swing.JButton jButton1;
    private javax.swing.JFormattedTextField jFormattedTextFieldDateRealisation;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel31;
    private javax.swing.JLabel jLabel32;
    private javax.swing.JLabel jLabel33;
    private javax.swing.JLabel jLabel34;
    private javax.swing.JLabel jLabel37;
    private javax.swing.JLabel jLabel38;
    private javax.swing.JLabel jLabel39;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel40;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel12;
    private javax.swing.JPanel jPanel13;
    private javax.swing.JPanel jPanel14;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel7;
    private javax.swing.JPanel jPanel8;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JTabbedPane jTabbedPane1;
    private javax.swing.JTextArea jTextAreaDescription;
    private javax.swing.JTextField jTextField3;
    private javax.swing.JTextField jTextFieldAdresse;
    private javax.swing.JTextField jTextFieldDateDemande;
    private javax.swing.JTextField jTextFieldDateNaissance;
    private javax.swing.JTextField jTextFieldDateObservation;
    private javax.swing.JTextField jTextFieldIPP;
    private javax.swing.JTextField jTextFieldIPP2;
    private javax.swing.JTextField jTextFieldNaturePrestation;
    private javax.swing.JTextField jTextFieldNom;
    private javax.swing.JTextField jTextFieldPH;
    private javax.swing.JTextField jTextFieldPHObservation;
    private javax.swing.JTextField jTextFieldPrenom;
    private javax.swing.JTextField jTextFieldSexe;
    private javax.swing.JTextPane jTextPaneAjoutResultat;
    private javax.swing.JList listeObservations;
    private javax.swing.JList listePrestations;
    private javax.swing.JPanel panelDouverture;
    // End of variables declaration//GEN-END:variables

}
